export {byType} from '../src/collect/compare/by-type';
export {compound} from '../src/collect/compare/compound';
export {following} from '../src/collect/compare/following';
export {isOneOf} from '../src/collect/compare/is-one-of';
export {matches} from '../src/collect/compare/matches';
export {natural} from '../src/collect/compare/natural';
export {normal} from '../src/collect/compare/normal';
export {reversed} from '../src/collect/compare/reversed';
export {withMap} from '../src/collect/compare/with-map';
