package(default_visibility = ["//:internal"])

load("//:defs.bzl", "gs_tools")

gs_tools(
    deps = [
        "//src/async",
        "//src/graph",
        "//src/store",
        "//src/string",
    ])