package(default_visibility = ["//:internal"])

load("//bazel/ts:defs.bzl", "ts_library")


ts_library(
    name = "angularjs",
    srcs = glob(["*.d.ts"]),
    deps = [
      "//declarations/jquery",
    ]
)
