package(default_visibility = ["//visibility:public"])

load("//:defs.bzl", "gs_tools")

gs_tools(
    deps = [
      "//src/data",
      "//src/inject",
      "//src/parse",
      "//src/string",
      "//src/ui",
      "//src/util",
    ])
