package(default_visibility = ["//visibility:public"])

load("//:defs.bzl", "gs_tools")

gs_tools(
    deps = [
      "//src/ui",
      "//src/util",
    ],
    test_deps = ["//src/testing:mock_angular"]
)
