package(default_visibility = ["//visibility:public"])

load("//:defs.bzl", "gs_tools")

gs_tools(
    deps = [
      "//src/collection",
      "//src/color",
      "//src/inject",
      "//src/mock",
      "//src/solver",
      "//src/testing",
      "//src/util",
      "//src/valid",
      "//src/webc",
    ])
